config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users
  resources :users, only: [:index, :edit, :update] do
    resources :clients, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :projects, only: [:new, :create, :edit, :update, :destroy] do
        resources :items, only: [:new, :create, :edit, :update, :destroy]

      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :last_name , presence: true
  validates :first_name, presence: true
  validates :phone_num , numericality: { only_integer: true }, length: { in: 10..11 }

  has_many :clients, dependent: :destroy
  has_many :projects, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def after_update_path_for(resource)
    user_path(current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    if user_signed_in?
    @clients = Client.where(user_id: current_user.id).order('created_at DESC')
    end
  end

  def edit
  end

  def update
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%= render "shared/header" %> 

<% if user_signed_in? %>
  <div class="d-flex justify-content-center mt-3 ">
    <h1 class="border-bottom border-danger text-center font-weight-bold" style="width:300px;">マイページ</h1>
  </div>
  <div class="container my-2 py-2 bg-light border border-dark rounded-lg">
    <div>
      <%= link_to 'プロフィール編集', edit_user_registration_path, class:"mr-3 btn btn-success text-nowrap border border-dark" %>
    </div>
    <h5>
    <div class="d-flex ml-5">
      <div>
        <div class="my-2">
        <%= "会社名"+"　　：　"+"#{current_user.company}" %>
        </div>
        <div class="my-2">
          <%= "住所"+"　　　：　"+"#{current_user.address}" %>
        </div>
        <div class="my-2">
          <%= "名前"+"　　　：　"+"#{current_user.last_name}"+" "+"#{current_user.first_name}" %>
        </div>
        <div class="my-2">
          <%= "電話番号"+"　：　"+"#{current_user.phone_num}" %>
        </div>
      </div>
    </div>
    <div class="px-1 mx-5 overflow-auto border border-dark rounded-lg bg-white" style="height:100px;">
      <%= current_user.info %>
    </div>
  </h5>
  <div>
    <%= link_to 'お客様登録', new_user_client_path(current_user.id), class:"mr-3 btn btn-primary text-nowrap border border-dark" %>
  </div>
  <% if @clients.blank? %>
  <%else%>
    <div class="ml-4">
      <h5>
        <ul>
          <% @clients.each do |client| %>
            <li>
              <div class="d-flex">
                <div class="my-1"  style="width:30%;">
                    <%= link_to "#{client.cli_last_name}"+" "+"#{client.cli_first_name}"+" "+"様",  user_clients_path(current_user.id,client_id:client.id), class:"text-decoration-none text-reset"%>
                </div>
                <div class="my-1 ">
                  <%= link_to "#{client.cli_company}",  user_clients_path(current_user.id,client_id:client.id), class:"text-decoration-none text-reset" %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </h5>
    </div>
  <% end %>
<% else %>
  <div class="mr-3 justify-content-center " style="height:300px;">
    <div class="d-flex justify-content-center mt-3 ">
      <h1 class="border-bottom border-danger text-center font-weight-bold" style="width:500px;">ログインしてください</h1>
    </div>
    <div style="height:50%;" class="bg-light border border-dark rounded-lg container my-2 py-2 d-flex align-items-center justify-content-center ">
        <%= link_to 'ログイン', new_user_session_path, class:"mx-5 btn btn-primary text-nowrap btn-lg" %>
        <%= link_to '新規登録', new_user_registration_path, class:"mx-5 btn btn-primary text-nowrap btn-lg" %>
    </div>
  </div>
<% end %>
</div>