config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users
  resources :users, only: [:index, :edit, :update] do
    resources :clients, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :projects, only: [:new, :create, :edit, :update, :destroy] do
        resources :items, only: [:new, :create, :edit, :update, :destroy]

      end
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord

  validates :cli_last_name, presence: true
  validates :cli_first_name, presence: true
  validates :cli_phone_num, numericality: { only_integer: true }, length: { in: 10..11 }

  belongs_to :user
  has_many :projects, dependent: :destroy
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!

  def index
    @client = Client.find(params[:client_id])
    @projects = Project.where(client_id: params[:client_id]).order('created_at DESC')
    if params[:project_id].blank?
      @project = Project.order(created_at: :desc).find_by(client_id: params[:client_id])
      if @project.blank?
      else
        @items = Item.where(project_id: @project.id).order('created_at DESC')
        if @items.blank?
        else
          @item = Item.order(created_at: :desc).find_by(project_id: @project.id)
        end
      end
    else
      @project = Project.find(params[:project_id])
      @items = Item.where(project_id: params[:project_id]).order('created_at DESC')
      if params[:item_id].blank?
        @item = Item.order(created_at: :desc).find_by(project_id: @project.id)
      else
        @item = Item.find(params[:item_id])
      end
    end
  end

  def new
    @client = Client.new

  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @client = Client.find(params[:id])
    if params[:project_id].blank?
    elsif params[:item_id].blank?
      @project = Project.find(params[:project_id])
    else
      @project = Project.find(params[:project_id])
      @item = Item.find(params[:item_id])
    end
  end

  def update
    @client = Client.find(params[:id])
    @client.update(client_params)
    @projects = Project.where(client_id: params[:id]).order('created_at DESC')
    if @client.save
      redirect_to  user_clients_path(client_id: params[:id],project_id: params[:project_id],item_id: params[:item_id])
    else
      render :edit
    end
  end

  def destroy
    client = Client.find(params[:id])
    client.destroy
    redirect_to root_path(current_user.id)
  end

  private

  def client_params
    params.require(:client).permit(:cli_email,:cli_company,:cli_last_name,:cli_first_name,:cli_last_kana,:cli_first_kana,:cli_address,:cli_phone_num,:cli_info).merge(user_id: current_user.id)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<%= render "shared/header" %>
<div class="d-flex justify-content-center mt-3 ">
  <h1 class="border-bottom border-danger text-center font-weight-bold" style="width:400px;">お客様情報詳細</h1>
</div>


<div class="justify-content-center " style="height:90%;">
  <div style="height:100%; " class="bg-light border border-dark container rounded-lg my-2 py-2">
    <% if @project.blank? %>
      <%= form_with model: @client, url: user_client_path(current_user.id), local: true do |f| %>   
        <%= render 'shared/error_messages', model: f.object %>
        <%= render 'shared/client_edit',{ f: f }%>
      <%end%>
    <%elsif @item.blank? %>
      <%= form_with model: @client, url: user_client_path(current_user.id,project_id:@project.id), local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
        <%= render 'shared/client_edit',{ f: f }%>
      <%end%>
    <%else%>
      <%= form_with model: @client, url: user_client_path(current_user.id,project_id:@project.id,item_id:@item.id), local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
        <%= render 'shared/client_edit',{ f: f }%>
      <%end%>
    <%end%>
  </div>
  <div class="mt-2 d-flex justify-content-center"> 
    <%= link_to "削除", user_client_path, method: :delete,class:"btn btn-danger text-nowrap btn-lg border border-dark"%>
  </div>  
</div>

app/views/clients/index.html.erb
<%= render "shared/header" %>
<div class="mx-2 mt-1 pb-2 fs-6 bg-light">
  <div class="d-flex mb-1">
    <div class="d-flex flex-column">
      <% if @project.blank? %>
        <div class="py-1 ml-0">
          <%= link_to 'お客様情報詳細', edit_user_client_path(current_user.id,id:@client.id), class:" mx-2 btn btn-success text-nowrap border border-dark" %>
        </div>
      <%elsif @item.blank? %>
        <div class="py-1 ml-0">
          <%= link_to 'お客様情報詳細', edit_user_client_path(current_user.id,id:@client.id,project_id:@project.id), class:" mx-2 btn btn-success text-nowrap border border-dark" %>
        </div>
      <%else%>
        <div class="py-1 ml-0">
          <%= link_to 'お客様情報詳細', edit_user_client_path(current_user.id,id:@client.id,project_id:@project.id,item_id:@item.id), class:" mx-2 btn btn-success text-nowrap border border-dark" %>
        </div>
      <%end%>
      <div class="ml-0">
          <%= link_to '新規御見積追加', new_user_client_project_path(current_user.id,client_id:@client.id), class:"my-1 mx-2 btn btn-primary text-nowrap border border-dark" %>
        </div>
    </div>
    <div class="pt-1 mt-1 ml-1 mr-2 d-flex flex-column " style="width:100%; height:85px;">
          <h5 class="font-weight-bold"><%= "#{@client.cli_company}"+"　"+"#{@client.cli_last_name}"+" "+"#{@client.cli_first_name}"+"　"+"様"%></h5>
          <div class="pl-1 overflow-auto border border-dark rounded-lg bg-white" style="height:100px;"><%= @client.cli_info %></div>
    </div>
  </div>
  <% if @projects.blank? %>
  <%else%>
    <div class="d-flex">
      <% if @project.blank? %>
      <%else%>
        <div class="mx-2 ">
          <div class="card border border-dark " style="width: 320px; height: 110px;">
            <div class="card-body ">
              <h5 class="font-weight-bold text-truncate ">
                <%= @project.pro_name %>
              </h5>
              <div class="d-flex flex-row">
                <div>
                  <div style="width: 110px;">
                    <%= @project.created_at.strftime('%Y/%m/%d')%>
                  </div>
                  <div style="width: 110px;">
                    No. <%= format("%08d", @project.id) %>
                  </div>
                </div>
                <div class=" ml-4 pl-4 py-2">
                      <%if @item.blank? %>
                      <%= link_to '御見積編集',edit_user_client_project_path(current_user.id, client_id:@client.id, id:@project.id) , class:"btn btn-success ml-2 border border-dark" %>
                      <%else%>
                      <%= link_to '御見積編集',edit_user_client_project_path(current_user.id, client_id:@client.id, id:@project.id, item_id:@item.id) , class:"btn btn-success ml-2 border border-dark" %>
                      <%end%>
                </div>
              </div>
            </div>
          </div>
        </div>
      <%end%>
      <div class="row flex-nowrap overflow-auto ml-0" >
        <% @projects.each do |projects| %>
            <%if @project.id == projects.id %>
            <%else%>
              <div class="mx-2 ">
                <div class="card border border-dark" style="width: 250px; height: 98px;">
                  <div class="card-body">
                    <div class="font-weight-bold text-truncate">
                      <%= projects.pro_name %>
                    </div>
                    <div class="d-flex flex-row" >
                      <div>
                        <div style="width: 110px;">
                          <%= projects.created_at.strftime('%Y/%m/%d')%>
                        </div>
                        <div style="width: 110px;">
                          No. <%= format("%08d", projects.id) %>
                        </div>
                      </div>
                      <div class=" ml-2 pl-4 mt-2 ">
                        <%= link_to '選択', user_clients_path(current_user.id, client_id:@client.id, project_id:projects.id), class:"btn btn-warning border border-dark",value: projects.id %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <%end%>
        <% end %>
      </div>
    </div>
    <% if @project.blank? %>
    <%else%>
      <div class = "mr-3">
        <div class=" ml-2 my-1 pl-1 border border-dark overflow-auto rounded-lg bg-white" style="width:100%; height:75px;"> 
          <% if @project.pro_info.blank? %>
          <%else%>
            <%= @project.pro_info %>
          <%end%>
        </div>
      </div>
      <div class=" border border-dark rounded-lg mx-2 pt-1">
        <div class="d-flex ">
          <div class="text-nowrap " style="width:240px;">
            <% link_to '印刷', "", class:" mx-2 btn btn-warning text-nowrap border border-dark" %>
            <%= link_to '新規商品追加',new_user_client_project_item_path(client_id:@client.id, project_id:@project.id), class:" mx-2 btn btn-primary text-nowrap border border-dark" %>
          </div>
          <div class="d-flex mr-2 justify-content-start" style="width:80%;"> 
            <h5 class="pt-2 text-nowrap font-weight-bold text-truncate" style="width:50%; height:35px;">
              <%= "件名：#{@project.pro_name}" %>
            </h5>
            <h5 class="ml-3 pt-2 px-2 text-nowrap font-weight-bold text-truncate" style="width:25%; height:35px;">
              <% all_price = 0 %>  
              <% @items.each do |item| %>
                <% all_price = all_price +(item.item_price * item.item_amount)%>
              <%end%>
              <%= "合計金額：#{all_price} 円" %>
            </h5>
            <h5 class="mx-2 pt-2 px-2 text-nowrap font-weight-bold text-truncate" style="width:25%; height:35px;">
              No. <%= format("%08d", @project.id) %>
            </h5>
          </div>
        </div> 
        <% if @project.items.ids.blank? %>
        <%else%>
          <div class="ml-2 ">
            <div class="d-flex d-flex justify-content-start">
              <div class="">
                <% @items.each do |item| %>
                  <% if item.id == @item.id%>
                    <%= link_to user_clients_path(current_user.id, client_id:@client.id, project_id:@project.id, item_id:item.id), class:"mb-1 text-nowrap justify-content-beteen rounded-pill border border-dark list-group-item list-group-item-action font-weight-bold", style:"width:220px;" do %> 
                      <div class="text-truncate "><%= item.item_name %><br> <%= item.item_price * item.item_amount%> 円</div>
                    <%end%>
                  <%else%>
                    <%= link_to user_clients_path(current_user.id, client_id:@client.id, project_id:@project.id, item_id:item.id), class:"mb-1 text-nowrap justify-content-beteen rounded-pill border border-dark list-group-item list-group-item-action font-weight-bold", style:"width:220px;" do %> 
                      <div class="text-truncate "><%= item.item_name %><br> <%= item.item_price * item.item_amount%> 円</div>
                    <%end%>
                  <%end%>
                <%end%>
              </div>
              <% if @item.blank? %> 
              <%else%>
                <div class="mx-2 mb-2 border border-dark rounded-lg bg-white overflow-auto" style="width:100%;">
                  <div class="mx-2 my-2"> 
                    <div class="d-flex " style="height:45px;" >
                      <div class="ml-1 pt-1"style="">
                        <%= link_to '商品編集', edit_user_client_project_item_path(current_user.id, client_id:@client.id, project_id:@project.id, id:@item.id), class:"border border-dark mx-2 btn btn-success text-nowrap mt-1" %>
                      </div>
                      <div class="d-flex pt-2 ml-3" style="width:90%;">
                        <div style="width:30%">
                          <h2 class=" font-weight-bold text-truncate" >価格：<%= @item.item_price * @item.item_amount%> 円</h2>
                        </div>
                        <div class="ml-4"style="width:60%">
                          <h2 class=" font-weight-bold text-truncate"><%= "商品名："+"#{@item.item_name}" %></h2>
                        </div>
                      </div>
                    </div>
                    <div class="mt-3 d-flex" style="width:100%;">
                      <div style="width:110px;">
                      </div>
                      <div>
                        <div class="mx-1"style="width:300px;">
                          <h4 >単価：<%= @item.item_price %> 円</h4> 
                        </div>
                        <div class="mx-1">
                          <h4>数量：<%= @item.item_amount %> 個</h4>
                        </div>
                      </div>
                    </div>
                    <div class="pl-1 overflow-auto border border-dark rounded-lg bg-white" style="height:200px;">
                      <%= @item.item_info %>
                    </div>
                  </div> 
                </div>
              <%end%>
              </div>
            </div>
          </div>
        <%end%> 
      </div>
    <%end%>
  <%end%>
</div>

app/views/clients/new.html.erb
<%= render "shared/header" %>
<div class="d-flex justify-content-center mt-3 ">
  <h1 class="border-bottom border-danger text-center font-weight-bold" style="width:400px;">お客様情報登録</h1>
</div>

<div class="justify-content-center " style="height:90%;">
  <div style="height:100%; " class="bg-light border border-dark container rounded-lg my-2 py-2 justify-content-center ">
    <%= form_with model: @client, url: user_clients_path, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="d-flex">   
        <div class="mr-5 my-2 " style="width:40%;">
          <%= f.label :姓%> <span class="text-danger">（必須）</span><em></em><br />
          <%= f.text_field :cli_last_name, autofocus: true, placeholder:"山田"%>
        </div>
      <div class="my-2 mr-5"  style="width:40%;">
          <%= f.label :名 %> <span class="text-danger">（必須）</span><em></em><br />
          <%= f.text_field :cli_first_name, placeholder:"太郎"%>
        </div>
      </div>
      <div class="d-flex">        
        <div class="my-2 mr-5" style="width:40%;">
          <%= f.label :会社名 %> <em></em><br />
          <%= f.text_field :cli_company, placeholder:"◯◯株式会社",style:"width:100%;"%>
        </div>
        <div class="my-2 mr-5" style="width:40%;">
          <%= f.label :電話番号 %> <span class="text-danger">（必須）</span><em></em><br />
          <%= f.text_field :cli_phone_num, placeholder:"123-4567-8910"%>
        </div>
      </div>
      <div class="my-2" >
        <%= f.label :住所 %> <em></em><br />
        <%= f.text_field :cli_address, placeholder:"住所", style:"width:100%;"%>
      </div>
      <div class="my-2" >
        <%= f.label :備考 %> <em></em><br />
        <%= f.text_area :cli_info, placeholder:"", style:"width:100%;"%>
      </div>

      <div class="my-2">
        <%= f.label :メールアドレス %><br />
        <%= f.email_field :cli_email, autofocus: true, autocomplete: "email", placeholder:"◯◯◯@example.com",style:"width:40%;"%>
      </div>


      <div class="actions mt-3 d-flex justify-content-center"> 
        <%= f.submit "登録" ,class:"btn btn-primary text-nowrap btn-lg border border-dark"%>
      </div>
    <% end %>
  </div>
</div>
    