config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users
  resources :users, only: [:index, :edit, :update] do
    resources :clients, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :projects, only: [:new, :create, :edit, :update, :destroy] do
        resources :items, only: [:new, :create, :edit, :update, :destroy]

      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord  

  validates :pro_name   , presence: true


  belongs_to :user
  belongs_to :client
  has_many :items, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def new
    @project= Project.new
    @client = Client.find(params[:client_id])
  end

  def create
    @project = Project.new(project_params)
    @client = Client.find(params[:client_id])
        if @project.save
      new_project = Project.order(created_at: :desc).find_by(params[:client_id])
      redirect_to user_clients_path(current_user.id,client_id:@client.id,project_id:new_project.id)
    else
      render :new
    end
  end

  def edit
    @project= Project.find(params[:id])
    @client = Client.find(params[:client_id])
    if params[:item_id].blank?
    else
      @item = Item.find(params[:item_id])
    end
  end

  def update
    @project = Project.find(params[:id])
    @client = Client.find(params[:client_id])
    @project.update(project_params)
    if @project.save
      redirect_to  user_clients_path(client_id:@client.id,project_id: params[:id],item_id: params[:item_id])
    else
      render :edit
    end
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to user_clients_path(current_user.id,client_id:params[:client_id])
  end
  private

  def project_params
    params.require(:project).permit(:pro_name,:pro_info).merge(user_id: current_user.id, client_id: params[:client_id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<%= render "shared/header" %>
<div class="d-flex justify-content-center mt-3 ">
  <h1 class="border-bottom border-danger text-center font-weight-bold" style="width:400px;">御見積編集</h1>
</div>
<div class="d-flex justify-content-center mt-3">
  <h4 class="font-weight-bold mt-1"><%= "#{@client.cli_company}"+"　"+"#{@client.cli_last_name}"+" "+"#{@client.cli_first_name}"+"　"+"様"%></h4>
</div>
<div class="justify-content-center " style="height:90%;">
  <%if @item.blank? %>
    <%= form_with model: @project, url: user_client_project_path(current_user.id,client_id:@client.id), local: true do |f| %>
      <div style="height:100%; " class="bg-light border border-dark container rounded-lg  py-2 justify-content-center ">
        <%= render 'shared/error_messages', model: f.object %>
        <%= render 'shared/project_edit',{ f: f }%>
      </div>
    <% end %>
  <%else%>
    <%= form_with model: @project, url: user_client_project_path(current_user.id,client_id:@client.id,item_id:@item.id), local: true do |f| %>
      <div style="height:100%; " class="bg-light border border-dark container rounded-lg  py-2 justify-content-center ">
        <%= render 'shared/error_messages', model: f.object %>
        <%= render 'shared/project_edit',{ f: f }%>
      </div>
    <% end %>
  <%end%>
  <div class="mt-2 d-flex justify-content-center"> 
    <%= link_to "削除", user_client_project_path, method: :delete,class:"btn btn-danger text-nowrap btn-lg border border-dark"%>
  </div>
<div>

app/views/projects/new.html.erb
<%= render "shared/header" %>
<div class="d-flex justify-content-center mt-3 ">
  <h1 class="border-bottom border-danger text-center font-weight-bold" style="width:400px;">新規御見積追加</h1>
</div>
<div class="d-flex justify-content-center mt-3">
  <h4 class="font-weight-bold mt-1"><%= "#{@client.cli_company}"+"　"+"#{@client.cli_last_name}"+" "+"#{@client.cli_first_name}"+"　"+"様"%></h4>
</div>
<div class="justify-content-center " style="height:90%;">
  <div style="height:100%; " class="bg-light border border-dark container rounded-lg  py-2 justify-content-center ">
    <%= form_with model: @project, url: user_client_projects_path, local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
          
      <div class="">
        <%= f.label :件名 %> <span class="text-danger">（必須）</span><em></em><br />
        <%= f.text_field :pro_name, placeholder:"件名", style:"width:100%;"%>
      </div>

      <div class="my-2">
        <%= f.label :備考 %> <em></em><br />
        <%= f.text_area :pro_info, placeholder:"",style:"width:100%;"%>
      </div>

      <div class="mt-3 d-flex justify-content-center"> 
        <%= f.submit "追加" ,class:"btn btn-primary text-nowrap btn-lg border border-dark"%>
      </div>
    <% end %>
  </div>
<div>