config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users
  resources :users, only: [:index, :edit, :update] do
    resources :clients, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :projects, only: [:new, :create, :edit, :update, :destroy] do
        resources :items, only: [:new, :create, :edit, :update, :destroy]

      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord

  validates :item_name, presence: true
  validates :item_price, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999, message: 'を正しく入力してください' }
  validates :item_amount, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999, message: 'を正しく入力してください' }

  belongs_to :project
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  def new
    @item= Item.new
    @client = Client.find(params[:client_id])
    @project = Project.find(params[:project_id])
  end

  def create
    @item = Item.new(item_params)
    @project = Project.find(params[:project_id])
    @client = Client.find(params[:client_id])
    if @item.save
      new_item = Item.order(created_at: :desc).find_by(params[:project_id])
      redirect_to user_clients_path(current_user.id,client_id:@project.client_id,project_id:@project.id,item_id:new_item.id)
    else
      render :new
    end
  end

  def edit
    @item= Item.find(params[:id])
    @client = Client.find(params[:client_id])
    @project = Project.find(params[:project_id])
  end

  def update
    @item = Item.find(params[:id])
    @project = Project.find(params[:project_id])
    @client = Client.find(params[:client_id])
    @item.update(item_params)
    if @item.save
      redirect_to user_clients_path(current_user.id,client_id:@project.client_id,project_id:@project.id,item_id:params[:id])
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to user_clients_path(current_user.id,client_id:params[:client_id],project_id:params[:project_id])
  end

  private

  def item_params
    params.require(:item).permit(:item_name,:item_price,:item_amount,:item_info).merge(project_id: params[:project_id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= render "shared/header" %>
<div class="d-flex justify-content-center mt-3 ">
  <h1 class="border-bottom border-danger text-center font-weight-bold" style="width:400px;">商品編集</h1>
</div>
<div class="d-flex justify-content-center mt-1">
  <h4 class="font-weight-bold mt-1"><%= "#{@client.cli_company}"+"　"+"#{@client.cli_last_name}"+" "+"#{@client.cli_first_name}"+"　"+"様"%></h4>
</div>
<div class="d-flex justify-content-center">
  <h4 class="font-weight-bold mt-1"><%=@project.pro_name%></h4>
</div>

<div class="justify-content-center " style="height:90%;">
  <%= form_with model: @item, url: user_client_project_item_path(project_id:@project.id), local: true do |f| %> 
    <div style="height:100%; " class="bg-light border border-dark container rounded-lg  py-2 justify-content-center ">
      <%= render 'shared/error_messages', model: f.object %>
          
      <div class="">
        <%= f.label :商品名 %> <span class="text-danger">（必須）</span><em></em><br />
        <%= f.text_field :item_name, autofocus: true, placeholder:"商品名",style:"width:40%;"%>
      </div>

      <div class="">
        <%= f.label :価格 %> <span class="text-danger">（必須）</span><em></em><br />
        <%= f.text_field :item_price, placeholder:"価格"%>
        円
      </div>

      <div class="">
        <%= f.label :数量 %> <span class="text-danger">（必須）</span><em></em><br />
        <%= f.text_field :item_amount, placeholder:"数量"%>
        個
      </div>

      <div class="my-2" >
        <%= f.label :商品説明 %> <em></em><br />
        <%= f.text_area :item_info, placeholder:"内容", style:"width:100%;"%>
      </div>

      <div class="mt-3 d-flex justify-content-center">
        <%= f.submit "更新",class:"btn btn-primary text-nowrap btn-lg border border-dark"%>
      </div>  
    </div>
    <div class="mt-2 d-flex justify-content-center"> 
      <%= link_to "削除", user_client_project_item_path, method: :delete,class:"btn btn-danger text-nowrap btn-lg border border-dark"%>
    </div>
  <% end %>
<div></div>

app/views/items/new.html.erb
<%= render "shared/header" %>
<div class="d-flex justify-content-center mt-3 ">
  <h1 class="border-bottom border-danger text-center font-weight-bold" style="width:400px;">新規商品追加</h1>
</div>
<div class="d-flex justify-content-center mt-1">
  <h4 class="font-weight-bold mt-1"><%= "#{@client.cli_company}"+"　"+"#{@client.cli_last_name}"+" "+"#{@client.cli_first_name}"+"　"+"様"%></h4>
</div>
<div class="d-flex justify-content-center">
  <h4 class="font-weight-bold mt-1"><%=@project.pro_name%></h4>
</div>

<div class="justify-content-center " style="height:90%;">
  <div style="height:100%; " class="bg-light border border-dark container rounded-lg  py-2 justify-content-center ">
    <%= form_with model: @item, url: user_client_project_items_path, local: true do |f|%>
      <%= render 'shared/error_messages', model: f.object %>
          
      <div class="">
        <%= f.label :商品名 %> <span class="text-danger">（必須）</span><em></em><br />
        <%= f.text_field :item_name, autofocus: true, placeholder:"商品名",style:"width:40%;"%>
      </div>

      <div class="">
        <%= f.label :価格 %> <span class="text-danger">（必須）</span><em></em><br />
        <%= f.text_field :item_price, placeholder:"価格"%>
        円
      </div>

      <div class="">
        <%= f.label :数量 %> <span class="text-danger">（必須）</span><em></em><br />
        <%= f.text_field :item_amount, placeholder:"数量"%>
        個
      </div>

      <div class="my-2" >
        <%= f.label :商品説明 %> <em></em><br />
        <%= f.text_area :item_info, placeholder:"内容", style:"width:100%;"%>
      </div>

      <div class="mt-3 d-flex justify-content-center"> 
        <%= f.submit "追加" ,class:"btn btn-primary text-nowrap btn-lg border border-dark"%>
      </div>
    <% end %>
  </div>
<div>